# Generated by Django 3.2.8 on 2021-12-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_postuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='postuser',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
