# Generated by Django 3.2.8 on 2021-12-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211225_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuser',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
